version: "3.8"
services:
  polkadot:
    container_name: polkadot
    image: docker.io/parity/polkadot:latest
    restart: unless-stopped
    # ports:
    #   - "9944:9944"
    command: '--chain polkadot --unsafe-ws-external --rpc-cors=all'

  sidecar:
    container_name: polkadot-sidecar
    image: docker.io/parity/substrate-api-sidecar:latest
    restart: unless-stopped
    read_only: true
    ports:
      - "8080:8080"
    environment:
      SAS_SUBSTRATE_WS_URL: ws://polkadot:9944
